language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.9
  - 2.2.6
  - 2.3.3
  - 2.4.0-rc1
  - jruby-19mode
  - jruby-9.1.5.0
  - rbx-3.9
gemfile:
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: jruby-19mode
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 2.1.9
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 2.2.5
      gemfile: gemfiles/rails_3.2.gemfile
    - rvm: 2.3.1
      gemfile: gemfiles/rails_3.2.gemfile
  allow_failures:
    - rvm: rbx-3.9
sudo: false
cache: bundler
addons:
  code_climate:
    repo_token: 4d712355fa2863c0f33f413eeede4e52cc221c4bc989a692d97574b1f6010b69
